name: Simple Check

on:
  push:
    branches: [ "main" ]

jobs:
  info-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show repo info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Author: ${{ github.actor }}"

      - name: List files
        run: ls -la

      - name: Check Python version
        run: python3 --version

      - name: Dummy test step
        run: echo "✅ Tests passed!"
