name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: test-job  # запускается после тестов
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-ci-image:latest .
